# Generated by Django 5.2.1 on 2025-06-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Market', '0001_initial'), ('Market', '0002_add_some_test'), ('Market', '0003_album_test'), ('Market', '0004_person_test2'), ('Market', '0005_album_test2')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('instrument', models.CharField(max_length=100)),
                ('test', models.CharField(default=213, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('test2', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_start', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.musician')),
                ('test', models.IntegerField(default=10)),
                ('test2', models.IntegerField(default=10)),
            ],
        ),
    ]
