# Generated by Django 5.2.1 on 2025-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='test',
            field=models.CharField(default=213, max_length=100),
            preserve_default=False,
        ),
    ]
