# Generated by Django 5.2.1 on 2025-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_add_some_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='test',
            field=models.IntegerField(default=10),
        ),
    ]
