# Generated by Django 5.2.1 on 2025-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_album_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test2',
            field=models.IntegerField(default=100),
        ),
    ]
