# Generated by Django 5.2.1 on 2025-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_person_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='test2',
            field=models.IntegerField(default=10),
        ),
    ]
