# Generated by Django 5.2.1 on 2025-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_squashed_0005_album_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор книги')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Кількість сторінок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Чи опубліковано')),
                ('status', models.CharField(choices=[('DR', 'Чернетка'), ('PB', 'Опубліковано'), ('AR', 'Архівовано')], default='DR', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='musician',
            name='test',
            field=models.CharField(max_length=100),
        ),
    ]
