# Generated by Django 5.2.1 on 2025-06-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('albums', models.ManyToManyField(blank=True, to='Market.album')),
            ],
        ),
    ]
