# Generated by Django 5.2.1 on 2025-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
