# Generated by Django 5.2.1 on 2025-07-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBV', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
